### PR TITLE
Added a pairing and ap for square

### PR DESCRIPTION
**Pull request by Alizter**
Added pairing (probably can find a better name) and and ap for Squares.

I am currently trying to formalise the Licata-Brunerie paper (at least the parts about the torus). It will give a good indication of what will be needed. These seem like fairly obvious things to add. It shouldn't be difficult (just tedious) to do the same for cubes too.

### CODE REVIEW

**Comment by mikeshulman** [comment]
Thanks!  To match the name of `path_prod` I would probably call it `square_prod`, what do you think?  Formalizing Licata-Brunerie is a great idea.

**Comment by mikeshulman** [comment]
Well, there's a tradeoff between evidentness of meaning and verbosity.  I was going for a concise convention on the naming that can be remembered and typed easily and quickly once you get used to it, analogous to the lemmas like `concat_pp_p` and `moveR_Mp` in the rest of the library.

**Comment by Alizter** [comment]
It may be worth sticking an underscore in there to make it clearer. sq_ap is miles clearer than sqap.

**Comment by mikeshulman** [comment]
Okay, fair enough.  If you want to do that (and do similarly for the others), go ahead.

**Pull request merged**
