### PR TITLE
Split up BlakersMassey into GBM, BlakersMassey and Freudenthal

### PR DESCRIPTION
**Pull request by Alizter**

### CODE REVIEW

**Comment by mikeshulman** [comment]
Why?

**Comment by Alizter** [comment]
@mikeshulman Are you asking why I have split up Blakers-Massey or Freudenthal? Freudenthal make sense to split up since you never say "by Blakers-Massey" when you use Freudenthal.

My reasoning for GBM: Since GBM is a theorem about modalities, once it is finished in full generality, it ought to be moved to Modalities. In the mean time any files written using the truncation case of BM will not need to be modified as a result.

**Comment by mikeshulman** [comment]
I don't think GBM should be moved to `Modalities`.  Although it *uses* modalities, it is a theorem of homotopy theory, so it belongs in `Homotopy`.  Classical BM is a trivial corollary of GBM, so I don't see a reason to break them into separate files.  And so is Freudenthal.  The theorem is named `freudenthal`, so there's no risk of saying `apply blakers_massey` when you mean `apply freudenthal`.

**Comment by Alizter** [comment]
If I am someone new to the library and I want to use Freudenthal, how will I know to look in Blakers-Massey?

**Comment by Alizter** [comment]
Also is GBM really a theorem about homotopy or a general theorem of the interaction of modalities with colimits. I suppose one could phrase GBM as a theorem about pushouts being (n+m)-seperated types with respect to some modality. Perhaps I am being stubborn but I really do think it is a theorem about modalities for modalities.

**Comment by Alizter** [comment]
OK I will retreat on my point about GBM since I can't really defend it right now. But I still think Freudenthal should be seperate.

**Pull request closed without merging**
